### ISSUE TITLE
Rasberry Pi

### ISSUE THREAD

**Issue by pmfortune** [PeteManchester/MediaPlayer#50]
Any chance of making a Raspberry Pi/HiFi Berry Micro SD image available for download.

Thanks

Peter

**Comment by PeteManchester** [comment]
Hi Peter,

No, I don't plan to release any images. I don't want to have to maintain multiple images for different DACs, also I don't have a Hifi Berry DAC..

If you want any help installing MediaPlayer I can help you with that.

For installing the HifiBerry DAC, have a look at this write up from Guus..

https://github.com/guussie/PiDS/wiki/09.-How-to-make-various-DACs-work

Thanks,

Pete.

**Comment by pmfortune** [comment]
Thanks

I’ll try and see how far I get.

I’m keen to get the install working with Mediaplayer as it will sit along side a Linn Sekrit amp I have and hopefully work together.

I’ll give you a shout if I get stuck! (Manchester based too!)

Thanks

Peter

**Comment by PeteManchester** [comment]
Hi Peter,

How did the install go?

What do you think of your Linn Sekrit?

Cheers,

Pete.

**Comment by clanger9** [comment]
Hi Pete,

It’s perfect! Appears in Kazoo, works like a charm. :-)
Apart from the three files with the ^M issue, everything else was fine.

My main Linn component is just a Majik DSM. Nothing flash, but the Pi player will enable me to extend the system to the rest of the house. Plus, the wife is happy because she likes to listen to suff from her Apple Mac over AirPlay, which also seems to work well.

I also used some of guussie’s refinements to tweak the config. https://github.com/guussie/PiDS/wiki/RPi-Digital-Streamer <https://github.com/guussie/PiDS/wiki/RPi-Digital-Streamer>

So far I’m just using the analogue-out on the Pi for testing. I haven’t decided on the amp yet - I have a spare pair of Tannoy D100 speakers so I’m probably rig them up to a combined DAC/class T amp like a Topping Vx1.

I plan to put some build instructions together to enable a complete newbie to build a working player...

Cheers,
Paul.

**Comment by pmfortune** [comment]
Great - got it working as well

Couple of minor glitches which I wonder if you might be able to help me with:

1) When I followed the instructions to put the Pi into performance mode it did’t work! It returned message: "bash: /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor: ambiguous redirect”. When issuing enquiry "cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor” it initially returned “powersave” but now says “ondemand”

2) When I reboot the pi the Mediaplayer starts but I can se it on any of the control points. As soon as I log into the pi and restart it it appears - any ideas?

3) Works beautify with Kinsky - seems to slug the performance of Kazoo control point (not a major issue but wonder what it might be)

Thanks for all your help

Peter-Marc

**Comment by PeteManchester** [comment]
Hi 

Sorry didn't notice the issue had been updated...

1) Not sure about the Performance mode, I've asked Guus if he has any ideas..

2) If you look at the log files for MediaPlayer can you see that MediaPlayer has started when the Pi is rebooted? Are you using wifi or lan or both?

3) Which part of Kazoo is slow , is it all, or when you select the PlayList source or Radio source etc..

Cheers,

Pete.

**Comment by guussie** [comment]
Peter-Marc,

1) I tried to replicate the behaviour you describe. I could not reproduce the error message, so thi may have been due to a typing error. However, I could reproduce the RPi going into on demand after having been set to performance mode. I tried to research this issue but so far I have not found the answer. I recollect that I read somewhere that on demand is actually OK for the type of use we have for the RPi, so this may be expected behaviour. While researching the issue I came across an interesting web site:

http://wiki.linuxaudio.org/wiki/raspberrypi

I will try the suggestions made on this site.

2) could it be that you have made a mistake in the procedure with the mediaplayer scripts? Perhaps you could try that again.

3) I don't seem to experience this. My NAS is a Raspberry Pi based system running minimserver.

I saw your forum entry in the Hifiberry forum. Have you solved your volume problem?
