### ISSUE TITLE
Airplay noice on start of track with iOS 11??

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#72]
I built three boxed mediaplayers for myself and two friends about two years ago now, and they have been running without a glitch for 24/7.
But about a month or so ago my friends said they where sometimes getting "pink noice" for a few seconds when starting airplay, when a new track gets going after a new connect. My first guess was that this might be related to something in iOS 11, as the box has not changed for two years now and the iOS update came out at about the same time.
So a week ago I unpacked and installed my own box, been in storage since I moved just before Christmas. At first I did not find anything wrong, but after a few weeks now I have heard the "glitch" two times.
First time produced static "pink noice" for a few seconds just after "play" in spotify on the iPhone. Then music and no further issue.
Seconds time I got more blip blop modem sounds, random beeps and some "pink noice", for a few seconds and then music.
As it only happens on the start of a new connect my first guess is that there is something going on with the encryption of the airplay stream, and my guess related to iOS 11.

Attached is debug log, from start of the player to playing a song where the first seconds are just noice and blip bloops.
Looks like the track starts at log row 2795, ish.

For songcast or upnp there seam to be no issues as all, it's only for airplay.

Mediaplayer is 0.0.8.7, Java 1.7.0_40

[mediaplayer.log.noice.zip](https://github.com/PeteManchester/MediaPlayer/files/1725753/mediaplayer.log.noice.zip)

**Comment by PeteManchester** [comment]
Hi,

Glad that it has been running without any issues for a while.

I would suggest setting the option 'airplay_audio_start_delay' to be true.
If set to true this option mutes the airplay audio for 2 seconds at the start of streaming. 
At the moment you have this option set to false.

2018-02-14 21:32:07,040 [main] FATAL [org.rpi.config.Config] 'airplay_audio_start_delay' : 'false'

I added the option because as you say sometimes there can be some pink noise at the start of the airplay stream.

Thanks,

Pete.
