### ISSUE TITLE
Radio: stop/pause button

### ISSUE THREAD

**Issue by e-roux** [PeteManchester/MediaPlayer#99]
Hello Pete,

I gave a try to the Lumin App as a control point on mac OS, work until now. It seems however that radio streams can not be stopped once on play. 

May be the reason a pause request can be sent because of the UI and awaited is a stop request in Mediaplayer? 

Thanks
Emmanuel

**Comment by PeteManchester** [comment]
Hi Emmanuel,

Please can you provide a bit more detail, such as which source you are playing the radio from, is it from a MediaServer or the configured radio list in MediaPlayer etc.. 
You say it works until now, has something changed? Did you upgrade mediaplayer etc.

Also if possible please could you provide the mediaplayer log file that covers when you try to stop the radio stream.

Thanks,

Pete.

**Comment by PeteManchester** [comment]
Hi Emmanuel,

I would say it is Lumin that is wrong, you are not supposed to be able to Pause a live radio stream, you can only Stop it.

However I have modified mediaplayer so that if a client sends a pause request for a radio channel it will stop playing the channel.

Please can you try the beta version that is here

https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/download/beta

and let me know the results.

Thanks,

Pete.
